version: '3'
  
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: todolist
      MYSQL_USER: todolist
      MYSQL_PASSWORD_FILE: /secrets/mysql-password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - './backend/secrets:/secrets'
  backend:
    build:
      context: ./backend
    image: todolist-backend:latest
    environment:
        DB_USER: todolist
        DB_HOST: db
        DB_NAME: todolist
        DB_PASS_FILE: /secrets/mysql-password
    ports:
      - "8080:8080"
    volumes:
      - './backend/secrets:/secrets'
    depends_on:
      - db
  dev:
    build:
      context: .
    image: todolist-dev:latest
    environment:
        DB_USER: todolist
        DB_HOST: db
        DB_NAME: todolist
        DB_PASS_FILE: /secrets/mysql-password
    ports:
      - "8080:8080"
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/backend/node_modules'
      - './backend/secrets:/secrets'
    depends_on:
      - db